Bootstrap: docker
From: python:3.6-slim

%post
    apt-get update && apt-get -y install python3-tk
    pip install --upgrade pip
    pip install --trusted-host pypi.python.org ipython
    pip install --trusted-host pypi.python.org numpy
    pip install --trusted-host pypi.python.org scipy
    pip install --trusted-host pypi.python.org pandas
    pip install --trusted-host pypi.python.org matplotlib
    mkdir -p /home/scotchcorner
